export const exchange = [
    'kraken',
    'bitfinex',
    'bithumb',
    'gate',
    'ftx_spot',
    'okex',
    'gdax',
    'hotbit',
    'binance',
    'poloniex',
    // 'kraken_futures',
    // 'bitfinex_futures',
    // 'bithumb_futures',
    // 'gate_futures',
    // 'ftx',
    // 'okex_swap',
    // 'binance_futures',
    // 'poloniex_futures'
]